---
title: "day1-10,000 of something"
author: "Kristen A, kkakey"
date: "1/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
```

```{r}
x <- seq(0,500,5)

prep_x <- seq(2.5,500,5)
x_half <- rep(prep_x, length(prep_x))
y <- sort(rep(prep_x, length(prep_x)))

df <- data.frame(y,x_half)

df$rnum <- sample(1:4, 10000, replace=T)
```

```{r}
ggplot(data=df) +
  geom_point(aes(x_half,y,shape=as.factor(rnum), color=as.factor(rnum)), size=2) +
  # geom_vline(xintercept=x) +
  # geom_hline(yintercept=x) +
  xlim(0, 500) +
  ylim(0, 500) +
  coord_fixed(expand = F, clip = "off") +
  theme_void() +
  theme(legend.position = "none",
        plot.background = element_rect(fill="#BA5F91", color=NA)) +
  scale_color_manual(values=rev(met.brewer("Austria",n=4,type="discrete"))) +
  ggsave("plot.png", height=10, width=10)

ggplot(data=df) +
  geom_point(aes(x_half,y,shape=as.factor(rnum), color=as.factor(rnum)), size=2) +
  xlim(0, 500) +
  ylim(0, 500) +
  coord_fixed(expand = F, clip = "off") +
  theme_void() +
  theme(legend.position = "none",
        plot.background = element_rect(fill="#2A0800", color=NA)) +
  scale_color_manual(values=met.brewer("Greek",n=4,type="discrete")) +
  ggsave("plot2.png", height=10, width=10)
```
